CREATE TABLE CURRENT_SERVICE (
SERVICE_ID int not null,
SERVICE_TYPE int not null,
V_ID int not null,
C_ID int not null,
REQUEST_DATE date not null, 
PRIMARY KEY (SERVICE_ID),
/*FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE_STATUS(SERVICE_ID)*/
/*FOREIGN KEY (V_ID) REFERENCES Vehicle (V_ID)*/  /*NEEDS CHECKING*/
/*FOREIGN KEY (C_ID) REFERENCES Customer (C_ID)*/
);
