SET IDENTITY_INSERT CoogTechSolutions.dbo.CURRENT_SERVICE OFF;
 INSERT INTO CoogTechSolutions.dbo.CURRENT_SERVICE (SERVICE_TYPE, V_ID, C_ID, REQUEST_DATE)
 VALUES (?,?,?,?)
, row.SERVICE_TYPE, row.V_ID, row.C_ID, row.REQUEST_DATE)