SET IDENTITY_INSERT CoogTechSolutions.dbo.CUSTOMER_CONTACT_INFO OFF;
 INSERT INTO CoogTechSolutions.dbo.CUSTOMER_CONTACT_INFO (C_PHONE,C_EMAIL, C_ADDRESS, C_ZIP, C_CITY, C_STATE)
 VALUES (?,?,?,?,?,?)
, row.C_PHONE, row.C_EMAIL, row.C_ADDRESS, row.C_ZIP, row.C_CITY, row.C_STATE)