SELECT
Customer.CUSTOMER_ID AS "Customer ID",
Customer.C_FNAME AS "First Name",
Customer.C_LNAME AS "Last Name",
STATE.STATE_NAME AS “STATE”,
CUSTOMER_VEHICLE.V_VIN AS "VIN",
VEHICLE.V_MAKE AS "Make",
VEHICLE.V_YEAR AS "Year",
VEHICLE.V_LICENSE_PLATE AS "License Plate"

FROM Customer
JOIN CUSTOMER_CONTACT_INFO
ON Customer.CUSTOMER_ID = CUSTOMER_CONTACT_INFO.CUSTOMER_ID
JOIN CUSTOMER_VEHICLE
ON Customer.CUSTOMER_ID = CUSTOMER_VEHICLE.CUSTOMER_ID
JOIN VEHICLE
ON CUSTOMER_VEHICLE.V_VIN = VEHICLE.V_VIN

ORDER BY CUSTOMER_CONTACT_INFO.STATE_NAME, Customer.CUSTOMER_ID


