SELECT
Customer.CUSTOMER_ID AS “Customer ID”,
Customer.C_FNAME AS “First Name”,
Customer.C_LNAME AS “Last Name”,
SERVICE_ORDER.SERVICE_ORDER_ID AS “Service”,
SERVICE_ORDER.DATE  AS “Date”,
SERVICE_ORDER.TOTAL_COST AS “Cost”

FROM Customer
JOIN CUSTOMER_ORDER
ON Customer_CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
JOIN SERVICE_ORDER
ON CUSTOMER_ORDER.SERVICE_ORDER_ID = SERVICE_ORDER.SERVICE_ORDER_ID

WHERE CUSTOMER.ACTIVE_ID = 3

ORDER BY Customer.CUSTOMER_ID
