SELECT
Customer.CUSTOMER_ID AS 'Customer ID',
Customer.C_FNAME AS 'First Name',
Customer.C_LNAME AS 'Last Name',
ISNULL(CUSTOMER.C_BUSINESS_NAME,'') AS 'Business Name',
SERVICE_ORDER.SERVICE_ORDER_ID AS 'Service ID',
SERVICE_ORDER.ORDER_DATE  AS 'Date'

FROM Customer
JOIN SERVICE_ORDER
ON Customer.CUSTOMER_ID = SERVICE_ORDER.CUSTOMER_ID

WHERE CUSTOMER.ACTIVE_ID = 3

ORDER BY Customer.CUSTOMER_ID
