SELECT
Customer.CUSTOMER_ID AS 'Customer Id',
Customer.C_FNAME AS 'First Name',
Customer.C_LNAME AS 'Last Name',
Customer.C_BUSINESS_NAME AS 'Business Name',
INSURANCE_COMPANY.INSURANCE_NAME AS 'Insurance Name',
INSURANCE_POLICY.POLICY_NAME AS 'Policy Name',
VEHICLE.V_VIN AS 'VIN'


FROM Customer
JOIN POLICY
ON Customer.CUSTOMER_ID = POLICY.CUSTOMER_ID
JOIN INSURANCE_POLICY
ON POLICY.POLICY_ID = INSURANCE_POLICY.POLICY_ID
JOIN INSURANCE_COMPANY
ON POLICY.INSURANCE_ID = INSURANCE_COMPANY.INSURANCE_ID
JOIN VEHICLE
ON POLICY.V_ID = VEHICLE.V_ID

WHERE (Customer.ACTIVE_ID = 1 OR Customer.ACTIVE_ID = 3) AND POLICY.POLICY_ID = 9

ORDER BY Customer.CUSTOMER_ID

