USE CoogTechSolutions

SELECT SERVICE_ORDER.SERVICE_ORDER_ID AS 'Order ID',
SERVICE_ORDER.ORDER_DATE AS 'Date Ordered',
SERVICE_ORDER_STATUS.ACTIVE_NAME AS 'Order Status' ,
FORMAT (INVOICE.TOTAL_COST, 'C') AS 'Cost',
Customer.C_LNAME AS 'Customer Last Name',
Customer.C_FNAME AS 'Customer First Name'

FROM SERVICE_ORDER
JOIN INVOICE
ON SERVICE_ORDER.SERVICE_ORDER_ID = INVOICE.SERVICE_ORDER_ID
JOIN SERVICE_ORDER_STATUS
ON SERVICE_ORDER.ACTIVE_ID = SERVICE_ORDER_STATUS.ACTIVE_ID
JOIN Customer
ON SERVICE_ORDER.CUSTOMER_ID = Customer.CUSTOMER_ID

WHERE YEAR(SERVICE_ORDER.ORDER_DATE) = YEAR(GETDATE()) AND SERVICE_ORDER.ORDER_DATE < GETDATE()

ORDER BY SERVICE_ORDER.ORDER_DATE;
