USE CoogTechSolutions

SELECT PART.PART_ID AS 'Part ID',
PART.PART_NAME AS 'Part Name',
SUPPLIER.SUPPLIER_NAME AS 'Supplier Name',
SUPPLIER.S_PHONE AS 'Phone Number',
SUPPLIER_PART.PART_COST AS 'Cost',
SUM(SERVICE_LINE.QUANTITY) AS 'Amount Used'

FROM PART
JOIN SUPPLIER_PART
ON PART.PART_ID = SUPPLIER_PART.PART_ID
JOIN SUPPLIER
ON SUPPLIER_PART.SUPPLIER_ID = SUPPLIER.SUPPLIER_ID
JOIN SERVICE_LINE_PART
ON PART.PART_ID = SERVICE_LINE_PART.PART_ID
JOIN SERVICE_LINE
ON SERVICE_LINE_PART.SERVICE_ORDER_ID = SERVICE_LINE.SERVICE_ORDER_ID
JOIN SERVICE_ORDER
ON SERVICE_LINE.SERVICE_ORDER_ID = SERVICE_ORDER.SERVICE_ORDER_ID

---find last year have not tested yet----
WHERE SERVICE_ORDER.ORDER_DATE < DATEADD(YEAR, -1, GETDATE());