USE CoogTechSolutions

SELECT Customer.CUSTOMER_ID AS 'Customer ID',
Customer.C_LNAME AS 'Last Name',
Customer.C_FNAME AS 'First Name',
INSURANCE_COMPANY.INSURANCE_NAME AS 'Insurance Name',
INSURANCE_POLICY.POLICY_NAME AS 'Policy Name',
POLICY.EXPIRATION_DATE AS 'Policy Expiration Date',
VEHICLE.V_ID AS 'VIN #'

FROM Customer
JOIN POLICY
ON Customer.CUSTOMER_ID = POLICY.CUSTOMER_ID
JOIN INSURANCE_POLICY
ON POLICY.POLICY_ID = INSURANCE_POLICY.POLICY_ID
JOIN INSURANCE_COMPANY
ON POLICY.INSURANCE_ID = INSURANCE_COMPANY.INSURANCE_ID
JOIN VEHICLE
ON POLICY.V_ID = VEHICLE.V_ID

WHERE POLICY.EXPIRATION_DATE > GETDATE();