USE CoogTechSolutions

SELECT VIOLATION.VIOLATION_NAME AS 'Violation Description',
VIOLATION.LAW_CODE AS 'Law Code Violated',
VIOLATION.VIOLATION_DATE AS 'Date of Occurance',
Customer.C_LNAME AS 'Owner Last Name',
Customer.C_FNAME AS 'Owner First Name',
VEHICLE.V_VIN AS 'VIN'

FROM VIOLATION
JOIN VEHICLE
ON VIOLATION.V_ID = VEHICLE.V_ID
JOIN CUSTOMER_VEHICLE
ON VEHICLE.V_ID = CUSTOMER_VEHICLE.V_ID
JOIN Customer
ON CUSTOMER_VEHICLE.CUSTOMER_ID = Customer.CUSTOMER_ID

WHERE YEAR(VIOLATION.VIOLATION_DATE) = Year(DATEADD(year,-1,GETDATE()));
