USE CoogTechSolutions

SELECT VIOLATION.VIOLATION_NAME AS 'Violation Description',
VIOLATION.LAW_CODE AS 'Law Code Violated',
VIOLATION.VIOLATION_DATE AS 'Date of Occurance',
STATE.STATE_NAME AS 'State',
COUNTRY.COUNTRY_NAME AS 'Country',
Customer.C_LNAME AS 'Owner Last Name',
Customer.C_FNAME AS 'Owner First Name',
VEHICLE.V_VIN AS 'VIN'

FROM VIOLATION
JOIN STATE_VIOLATION
ON VIOLATION.VIOLATION_ID = STATE_VIOLATION.VIOLATION_ID
JOIN STATE
ON STATE_VIOLATION.STATE_ID = STATE.STATE_ID
JOIN COUNTRY
ON STATE.COUNTRY_ID = COUNTRY.COUNTRY_ID
JOIN CUSTOMER_STATE
ON STATE.STATE_ID = CUSTOMER_STATE.STATE_ID
JOIN Customer
ON CUSTOMER_STATE.CUSTOMER_ID = Customer.CUSTOMER_ID
JOIN VEHICLE
ON VIOLATION.V_ID = VEHICLE.V_ID

WHERE YEAR(VIOLATION.VIOLATION_DATE) = YEAR(GETDATE()) AND VIOLATION.VIOLATION_DATE < GETDATE();