USE CoogTechSolutions
CREATE TABLE dbo.CURRENT_SERVICE (
	SERVICE_ID int not null,
	SERVICE_TYPE varchar(30) not null,
	V_VIN int not null,
	C_ID int not null,
	REQUEST_DATE date not null, 
	PRIMARY KEY (SERVICE_ID),
	FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE_ORDER_LINE(SERVICE_ID),
	FOREIGN KEY (V_VIN) REFERENCES VEHICLE(V_VIN),
	FOREIGN KEY (C_ID) REFERENCES Customer(C_ID)
);
