USE CoogTechSolutions
CREATE TABLE dbo.SERVICE_ORDER_LINE (
    SERVICE_ID INT PRIMARY KEY
    ORDER_ID INT,
    SERVICE_DATE DATETIME,
    ITEM_QTY INT,
    ITEM_COST FLOAT,
    LABOR_HOURS FLOAT,
	FOREIGN KEY (SERVICE_ID) REFERENCES Service(SERVICE_ID),
)
