CREATE TABLE FINSHED_ORDER (
    SERVICE_ID int PRIMARY KEY,
	ORDER_ID int,
    DATE_START DATETIME,
    DATE_END DATETIME NOT NULL,
    Quality text,
	FOREIGN KEY (SERVICE_ID) REFERENCES Service(SERVICE_ID)
);
