USE CoogTechSolutions

SELECT SUPPLIER.SUPPLIER_NAME AS 'Supplier', PART.PART_NAME AS 'Part', EMPLOYEE.EMPLOYEE_ID AS 'Employee ID', 
EMPLOYEE.EMPLOYEE_LNAME AS 'Last Name', EMPLOYEE.EMPLOYEE_FNAME AS 'First Name', COUNT(PART.PART_ID) AS 'Part Amount'

FROM EMPLOYEE
JOIN Employee_Status
ON Employee_Status.ACTIVE_ID = EMPLOYEE.ACTIVE_ID
JOIN EMPLOYEE_SERVICE_LINE_ASSIGNMENT
ON EMPLOYEE.EMPLOYEE_ID = EMPLOYEE_SERVICE_LINE_ASSIGNMENT.EMPLOYEE_ID
JOIN SERVICE_LINE
ON EMPLOYEE_SERVICE_LINE_ASSIGNMENT.SERVICE_ORDER_ID = SERVICE_LINE.SERVICE_ORDER_ID AND EMPLOYEE_SERVICE_LINE_ASSIGNMENT.SERVICE_ID = SERVICE_LINE.SERVICE_ID
JOIN SERVICE_LINE_PART
ON SERVICE_LINE_PART.SERVICE_ORDER_ID = SERVICE_LINE.SERVICE_ORDER_ID AND SERVICE_LINE_PART.SERVICE_ID = SERVICE_LINE.SERVICE_ID
JOIN PART
ON SERVICE_LINE_PART.PART_ID = PART.PART_ID
JOIN SUPPLIER_PART
ON PART.PART_ID = SUPPLIER_PART.PART_ID
JOIN SUPPLIER
ON SUPPLIER_PART.SUPPLIER_ID = SUPPLIER.SUPPLIER_ID

WHERE Employee_Status.ACTIVE_ID = 1
GROUP BY SUPPLIER.SUPPLIER_NAME, PART.PART_NAME, EMPLOYEE.EMPLOYEE_ID,EMPLOYEE.EMPLOYEE_LNAME, EMPLOYEE.EMPLOYEE_FNAME
ORDER BY PART.PART_NAME, EMPLOYEE_LNAME;