USE CoogTechSolutions

SELECT SUPPLIER.SUPPLIER_NAME AS "Supplier", PART.PART_NAME AS "Part", EMPLOYEE.EMPLOYEE_ID AS "Employee ID", 
EMPLOYEE.EMPLOYEE_LNAME AS "Last Name", EMPLOYEE.EMPLOYEE_FNAME AS "First Name"

FROM EMPLOYEE
JOIN Employee_Status
ON Employee_Status.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID
JOIN EMPLOYEE_SERVICE_LINE_ASSIGNMENT
ON EMPLOYEE.EMPLOYEE_ID = EMPLOYEE_SERVICE_LINE_ASSIGNMENT.EMPLOYEE_ID
JOIN SERVICE_LINE
ON EMPLOYEE_SERVICE_LINE_ASSIGNMENT.SERVICE_LINE_ID = SERVICE_LINE.SERVICE_LINE_ID
JOIN SERVICE_LINE_PART
ON SERVICE_LINE.SERVICE_LINE_ID = SERVICE_LINE_PART.SERVICE_LINE_ID
JOIN PART
ON SERVICE_LINE_PART.PART_ID = PART.PART_ID
JOIN SUPPLIER_PART
ON PART.PART_ID = SUPPLIER_PART.PART_ID
JOIN SUPPLIER
ON SUPPLIER_PART.SUPPLIER_ID = SUPPLIER.SUPPLIER_ID

WHERE Employee_Status.ACTIVE_ID = 1
ORDER BY PART.PART_NAME;