USE CoogTechSolutions

SELECT Customer.C_FNAME AS 'First Name', Customer.C_LNAME AS 'Last Name', CUSTOMER_TYPE.BUSINESS AS 'Type', 
CUSTOMER_STATUS.ACTIVE_NAME,
Customer.C_PHONE AS 'Phone', Customer.C_EMAIL AS 'Email'

FROM Customer
JOIN CUSTOMER_STATUS
ON Customer.ACTIVE_ID = CUSTOMER_STATUS.ACTIVE_ID
JOIN SERVICE_ORDER
ON Customer.CUSTOMER_ID = SERVICE_ORDER.CUSTOMER_ID
JOIN CUSTOMER_TYPE
ON CUSTOMER_TYPE.BUSINESS_ID = Customer.BUSINESS_ID

WHERE Customer.ACTIVE_ID = 2 OR Customer.ACTIVE_ID = 4 /*OR SERVICE_ORDER.ORDER_DATE < GETDATE()*/
ORDER BY CUSTOMER.C_LNAME, CUSTOMER.C_FNAME;
