USE CoogTechSolutions

SELECT Customer.C_FNAME AS "First Name", Customer.C_LNAME AS "Last Name", CUSTOMER_STATUS.ACTIVE, SERVICE_ORDER.ORDER_DATE, GETDATE()

FROM Customer
JOIN CUSTOMER_STATUS
ON Customer.CUSTOMER_ID = CUSTOMER_STATUS.CUSTOMER_ID
JOIN CUSTOMER_ORDER
ON Customer.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
JOIN SERVICE_ORDER
ON CUSTOMER_ORDER.SERVICE_ORDER_ID = SERVICE_ORDER.SERVICE_ORDER_ID

WHERE CUSTOMER_STATUS.C_ACTIVE = 2 OR CUSTOMER_STATUS.C_ACTIVE = 4 /*OR SERVICE_ORDER.ORDER_DATE < GETDATE()*/
ORDER BY CUSTOMER.C_LNAME, CUSTOMER.C_FNAME;
