USE CoogTechSolutions

SELECT Customer.CUSTOMER_ID, VEHICLE.YEAR, VEHICLE.MAKE, VEHICLE.MODEL, SUPPLIER.SUPPLIER_NAME, SUPPLIER_PART.SUP_PART_NAME
FROM CUSTOMER
JOIN INVOICE
ON Customer.CUSTOMER_ID = INVOICE.CUSTOMER_ID
JOIN INVOICE_PAYMENT
ON INVOICE.INVOICE_ID = INVOICE_PAYMENT.INVOICE_ID
JOIN PAYMENT
ON INVOICE_PAYMENT.PMT_NUMBER = PAYMENT.PMT_NUMBER
JOIN ACCOUNT_REVENUE
ON PAYMENT_REVENUE.REVENUE_ID = ACCOUNT_REVENUE.REVENUE_ID
ORDER BY INVOICE.INVOICE_DATE