USE CoogTechSolutions

SELECT Customer.CUSTOMER_ID AS "Customer ID", Customer.C_LNAME AS "Last Name", Customer.C_FNAME AS "First Name",
ACCOUNT_REVENUE.REVENUE_NAME AS "Revenue Name", SERVICE.SERVICE_TYPE AS "SERVICE NAME", ACCOUNT_REVENUE.REVENUE_VALUE AS "Revenue Value"

FROM CUSTOMER
JOIN CUSTOMER_CONTACT_INFO
JOIN SERVICE_ORDER
ON CUSTOMER_ORDER.SERVICE_ORDER_ID = SERVICE_ORDER.SERVICE_ORDER_ID
JOIN SERVICE_LINE
ON SERVICE_LINE.SERVICE_ORDER_ID = SERVICE_ORDER.SERVICE_ORDER_ID
JOIN SERVICE
ON SERVICE.SERVICE_ID = SERVICE_LINE.SERVICE_ID
JOIN INVOICE
ON Customer.CUSTOMER_ID = INVOICE.CUSTOMER_ID
JOIN INVOICE_PAYMENT
ON  INVOICE.INVOICE_ID = INVOICE_PAYMENT.INVOICE_ID
JOIN PAYMENT
ON INVOICE_PAYMENT.PMT_NUMBER = PAYMENT.PMT_NUMBER
JOIN PAYMENT_REVENUE
ON PAYMENT.PMT_NUMBER = PAYMENT_REVENUE.PMT_NUMBER
JOIN ACCOUNT_REVENUE
ON PAYMENT_REVENUE.REVENUE_ID = ACCOUNT_REVENUE.REVENUE_ID

ORDER BY INVOICE.INVOICE_DATE;