USE CoogTechSolutions

SELECT VEHICLE_SERVICE.V_VIN AS "VIN", VEHICLE.YEAR, VEHICLE.MAKE, VEHICLE.MODEL, SUPPLIER_NAME, SUP_PART_NAME
FROM VEHICLE
JOIN VEHICLE_SERVICE
ON VEHICLE.V_VIN = VEHICLE_SERVICE.V_VIN
JOIN SERVICE
ON VEHICLE_SERVICE.SERVICE_ID = SERVICE.SERVICE_ID


JOIN SUPPLIER
ON SUPPLIER.SUPPLIER_ID = SUPPLIER_PART.SUPPLIER_ID
