CREATE TABLE State(

C_STATE varchar(15) PRIMARY KEY not null,
LAW_CODE varchar(15) not null,
  
 FOREIGN KEY (C_STATE) REFERENCES CUSTOMER_CONTACT_INFO(C_STATE),
 FOREIGN KEY (C_ID) REFERENCES CUSTOMER_CONTACT_INFO(C_ID)
 
/*Zach Kurtubi*/
);
