USE CoogTechSolutions
-------------------------Darrian-----------------------------------------------------
--Alter Payment--
ALTER TABLE PAYMENT
add CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID);
--Alter Service Order Line--
ALTER TABLE SERVICE_ORDER_LINE
add CONSTRAINT ORDER_ID_FK FOREIGN KEY (ORDER_ID) REFERENCES FINSIHED_ORDER(ORDER_ID);
--Alter Finsihed Order--
ALTER TABLE FINSIHED_ORDER
add CONSTRAINT ORDER_ID_FK FOREIGN KEY (ORDER_ID) REFERENCES SERVICE_REQUEST(ORDER_ID);

----------------------------Anthony-----------------------------------------------------
--Alter Invoice--
ALTER TABLE INVOICE
add CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID);

---------------------------Mustafa------------------------------------------------------
--CUSTOMER CONTACT INFO ALTER
ALTER TABLE CUSTOMER_CONTACT_INFO
add CONSTRAINT C_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
CONSTRAINT C_STATE_FK FOREIGN KEY (C_STATE) REFERENCES STATE(C_STATE);
----CURRENT SERVICE ALTER 
ALTER TABLE CURRENT_SERVICE
add CONSTRAINT ORDER_ID_FK FOREIGN KEY (ORDER_ID) REFERENCES SERVICE_REQUEST(ORDER_ID),
CONSTRAINT V_VIN_FK FOREIGN KEY (V_VIN) REFERENCES VEHICLE(V_VIN),
CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID);

-------------------------jahidul----------------------------------------------------------------
--Alter Customer Request--
ALTER TABLE CUSTOMER_REQUEST
add CONSTRAINT ORDER_ID_FK FOREIGN KEY (ORDER_ID) REFERENCES SERVICE_REQUEST(ORDER_ID);
--Alter Customer Vehicle--
ALTER TABLE CUSTOMER_VEHICLE
add CONSTRAINT V_VIN_FK FOREIGN KEY (V_VIN) REFERENCES VEHICLE(V_VIN);
--Alter Vehicle Policy--
ALTER TABLE VEHICLE_POLICY
add CONSTRAINT POLICY_ID_FK FOREIGN KEY (POLICY_ID) REFERENCES INSURANCE_POLICY(POLICY_ID);
--Alter Company Insurance policy--
ALTER TABLE COMPANY_INSURANCE_POLICY
add CONSTRAINT POLICY_ID_FK FOREIGN KEY (POLICY_ID) REFERENCES INSURANCE_POLICY(POLICY_ID);

---------------------------Jerry---------------------------------------------------------------
-- Alter Insurance Company--
ALTER TABLE INSURANCE_COMPANY
add CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID);
--Alter Insurance Policy--
ALTER TABLE INSURANCE_POLICY
add CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID),
CONTSTRAINT INSURANCE_ID_FK FOREIGN KEY (INSURANCE_ID) REFERENCES INSURANCE_COMPANY(INSURANCE_ID);

