USE CoogTechSolutions
-------------------------Darrian-----------------------------------------------------
--Alter Payment--
ALTER TABLE PAYMENT
add CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID);
--Alter Service Order Line--
ALTER TABLE SERVICE_ORDER_LINE
add CONSTRAINT ORDER_ID_FK FOREIGN KEY (ORDER_ID) REFERENCES FINSIHED_ORDER(ORDER_ID);
--Alter Finsihed Order--
ALTER TABLE FINSIHED_ORDER
add CONSTRAINT ORDER_ID_FK FOREIGN KEY (ORDER_ID) REFERENCES SERVICE_REQUEST(ORDER_ID);
----------------------------Anthony-----------------------------------------------------


---------------------------Mustafa------------------------------------------------------
--CUSTOMER CONTACT INFO ALTER
ALTER TABLE CUSTOMER_CONTACT_INFO
add CONSTRAINT C_ID_FK FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID);

----CURRENT SERVICE ALTER 
ALTER TABLE CURRENT_SERVICE
add CONSTRAINT ORDER_ID_FK FOREIGN KEY (ORDER_ID) REFERENCES SERVICE_REQUEST(ORDER_ID);
ALTER TABLE CURRENT_SERVICE
add CONSTRAINT V_VIN_FK FOREIGN KEY (V_VIN) REFERENCES VEHICLE(V_VIN);
ALTER TABLE CURRENT_SERVICE
add CONSTRAINT C_ID_FK FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID);
