CREATE TABLE SERVICE_ORDER_LINE (
    /*SERVICE_ID INT FOREIGN KEY REFERENCES Service(SERVICE_ID),*/
    ORDER_ID INT PRIMARY KEY,
    SERVICE_DATE DATETIME,
    ITEM_QTY INT,
    ITEM_COST FLOAT,
    LABOR_HOURS FLOAT
)