USE CoogTechSolutions
-------------------Darrian-------------------------------
CREATE TABLE dbo.Customer (
    CUSTOMER_ID int IDENTITY(1,1) NOT NULL,
    C_LNAME varchar(25) NOT NULL,
    C_FNAME varchar(25),
    C_BUSINESS_NAME varchar(50),
	CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE dbo.PAYMENT (
    PMT_NUMBER int NOT NULL,
	PMT_ID int NOT NULL,
	PMT_TYPE VARCHAR(10) NOT NULL,
    AMT_PAID MONEY,
	CONSTRAINT PMT_NUMBER_PK PRIMARY KEY (PMT_NUMBER)
);
CREATE TABLE dbo.SERVICE_LINE (
    SERVICE_LINE_ID INT IDENTITY(1,1) NOT NULL,
	SERVICE_ID INT NOT NULL,
	SERVICE_ORDER_ID INT NOT NULL,
    LINE_DATE DATETIME,
	LINE_COST MONEY,
	CONSTRAINT SERVICE_LINE_ID_PK PRIMARY KEY (SERVICE_LINE_ID)
);
CREATE TABLE dbo.INVOICE_PAYMENT (
	PMT_NUMBER int NOT NULL,
    INVOICE_ID int NOT NULL,
	CONSTRAINT PMT_NUMBER_PK1 PRIMARY KEY (PMT_NUMBER)
);
-----------------Anthony-------------------------------
--Employee Create Script--
CREATE TABLE dbo.EMPLOYEE (
	EMPLOYEE_ID int IDENTITY(1,1) NOT NULL,
	EMPLOYEE_LNAME varchar(30) not null,
	EMPLOYEE_FNAME varchar(30) not null,
	EMPLOYEE_ADDRESS varchar(50) not null,
	EMPLOYEE_HIRE_DATE DATETIME,
	EMPLOYEE_HOURS int,
	EMPLOYEE_PAY_RATE MONEY,
	EMPLOYEE_PHONE bigint not null,
	EMPLOYEE_BANK_INFO bigint,
	EMPLOYEE_TAX int,
	EMPLOYEE_JOB_FUNC varchar(30),
	CONSTRAINT EMPLOYEE_ID_PK PRIMARY KEY (EMPLOYEE_ID)
);
--Supplier Create Script--
CREATE TABLE dbo.SUPPLIER (
	SUPPLIER_ID int IDENTITY(1,1) not null,
	SUPPLIER_NAME varchar(50),
	CONSTRAINT SUPPLIER_ID_PK PRIMARY KEY (SUPPLIER_ID)
);

--Service Status Create--
CREATE TABLE dbo.SERVICE_ORDER_STATUS (
    SERVICE_ORDER_ID int NOT NULL,
    ACTIVE_ID int NOT NULL,
    ACTIVE varchar(15),
	CONSTRAINT SERVICE_ORDER_ID_PK1 PRIMARY KEY (SERVICE_ORDER_ID)
);

--Create Invoice--
CREATE TABLE dbo.INVOICE (
	INVOICE_ID int IDENTITY(1,1) not null,
	CUSTOMER_ID int not null,
	TOTAL_COST MONEY,
	AMT_OWED MONEY,
	INVOICE_DATE date not null,
	CONSTRAINT INVOICE_ID_PK PRIMARY KEY (INVOICE_ID),
);

------------------Mustafa-----------------------------------------------
--Service Line Status--
CREATE TABLE dbo.SERVICE_LINE_STATUS (
	SERVICE_LINE_ID int not null,
	ACTIVE_ID int not null,
	ACTIVE varchar(20),
	CONSTRAINT SERVICE_LINE_ID_PK1 PRIMARY KEY (SERVICE_LINE_ID)
);
--customer contact--
CREATE TABLE dbo.CUSTOMER_CONTACT_INFO (
	CUSTOMER_ID INT not null,
	C_PHONE varchar(15)  not null,
	C_EMAIL varchar(30) not null,
	C_ADDRESS varchar(30) not null,
	C_ZIP INT not null,
	C_CITY varchar(30) not null,
	STATE_NAME varchar(10) not null,
	CONSTRAINT CUSTOMER_ID_PK1 PRIMARY KEY(CUSTOMER_ID)
);
--VEHICLE STATUS--
CREATE TABLE dbo.VEHICLE_STATUS (
	V_VIN varchar(20) not null,
	ACTIVE_ID int not null,
	ACTIVE varchar(20),
	CONSTRAINT V_VIN_PK1 PRIMARY KEY (V_VIN)
);
--PAYMENT REVENUE--
create table dbo.PAYMENT_REVENUE(
	REVENUE_ID int not null,
	PMT_NUMBER int not null,
	CONSTRAINT REVENUE_ID_PK1 PRIMARY KEY (REVENUE_ID)
);
------------Jahidul---------------------------------------------------
create table dbo.CUSTOMER_ORDER(
	SERVICE_ORDER_ID int not null,
	CUSTOMER_ID int not null,
	CONSTRAINT SERVICE_ORDER_ID_PK2 PRIMARY KEY (SERVICE_ORDER_ID)
);
create table dbo.CUSTOMER_VEHICLE(
	V_VIN varchar(20) not null,
	CUSTOMER_ID int not null,
	CONSTRAINT V_VIN_PK2 PRIMARY KEY (V_VIN)
);
create table dbo.VEHICLE_POLICY(
	V_VIN varchar(20) not null,
	POLICY_ID int not null,
	CONSTRAINT V_VIN_PK4 PRIMARY KEY (V_VIN)
);
create table dbo.COMPANY_INSURANCE_POLICY(
	INSURANCE_ID int not null,
	POLICY_ID int not null,
	CONSTRAINT INSURANCE_ID_PK1 PRIMARY KEY (INSURANCE_ID)
);
----------------------------Kyle--------------------------------------
CREATE TABLE dbo.VEHICLE_SERVICE(
	SERVICE_ID INT NOT NULL,
	V_VIN VARCHAR(20) NOT NULL,
	CONSTRAINT SERVICE_ID_PK2 PRIMARY KEY (SERVICE_ID)
);
CREATE TABLE dbo.CUSTOMER_STATUS (
	CUSTOMER_ID INT NOT NULL,
	C_ACTIVE INT NOT NULL,
	ACTIVE VARCHAR(20) NOT NULL
	CONSTRAINT CUSTOMER_ID_PK2 PRIMARY KEY (CUSTOMER_ID)

);
CREATE TABLE dbo.SUPPLIER_STATUS(
	SUPPLIER_ID INT NOT NULL,
	ACTIVE_ID INT NOT NULL,
	ACTIVE VARCHAR(15) NOT NULL,
	CONSTRAINT SUPPLIER_ID_PK1 PRIMARY KEY (SUPPLIER_ID)
);
CREATE TABLE dbo.VEHICLE(
	V_VIN VARCHAR(20) NOT NULL,
	V_MAKE VARCHAR(15),
	V_MODEL VARCHAR(15),
	V_YEAR INT,
	V_LISCENSE_PLATE VARCHAR(15) NOT NULL,
	CONSTRAINT V_VIN_PK PRIMARY KEY (V_VIN)
);
--------------------------------Brandon--------------------------------
CREATE TABLE dbo.PART (
  PART_ID INT IDENTITY(1,1) NOT NULL,
  PART_NAME varchar(50),
  CONSTRAINT PART_ID_PK1 PRIMARY KEY (PART_ID)
 );
CREATE TABLE dbo.EMPLOYEE_SERVICE_LINE_ASSIGNMENT (
  SERVICE_LINE_ID INT NOT NULL,
  EMPLOYEE_ID INT NOT NULL,
  CONSTRAINT SERVICE_LINE_ID_PK2 PRIMARY KEY (SERVICE_LINE_ID)
);
CREATE TABLE dbo.SERVICE (
  SERVICE_ID INT not null,
  SERVICE_TYPE VARCHAR(75) not null,
  DATE_START DATETIME NOT NULL,
  DATE_END DATETIME,
  COST MONEY NOT NULL,
  CONSTRAINT SERVICE_ID_PK PRIMARY KEY (SERVICE_ID)
);
CREATE TABLE dbo.SERVICE_LINE_PART(
  SERVICE_LINE_ID INT NOT NULL,
  PART_ID INT NOT NULL,
  CONSTRAINT SERVICE_LINE_ID_PK3 PRIMARY KEY (SERVICE_LINE_ID)
);
--------------------------------Maddy------------------------------------
CREATE TABLE dbo.COUNTRY (
	COUNTRY_ID int IDENTITY(1,1) not null,
	COUNTRY_NAME varchar(60) not null,
	CONSTRAINT COUNTRY_ID_PK PRIMARY KEY (COUNTRY_ID)
);
CREATE TABLE dbo.CUSTOMER_TYPE (
	CUSTOMER_ID int not null,
	IS_BUSINESS BIT not null,
	CONSTRAINT CUSTOMER_ID_PK3 PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE dbo.EMPLOYEE_LOOKUP (
	EMPLOYEE_ID int not null,
	EMPLOYEE_CURR_SERVICE varchar(40) not null,
	CONSTRAINT EMPLOYEE_ID_PK1 PRIMARY KEY (EMPLOYEE_ID)
);
CREATE TABLE dbo.SERVICE_ORDER (
	SERVICE_ORDER_ID int IDENTITY(1,1) not null,
	ORDER_DATE datetime,
	TOTAL_COST MONEY,
	CONSTRAINT SERVICE_ORDER_ID_PK PRIMARY KEY (SERVICE_ORDER_ID)
);
------------------------------Giancarlos------------------------------------
CREATE TABLE dbo.SUPPLIER_LOOKUP (
    SUPPLIER_ID INT NOT NULL,
    PART_ID INT NOT NULL,
    CONSTRAINT SUPPLIER_ID_PK2 PRIMARY KEY (SUPPLIER_ID)
);
CREATE TABLE dbo.VIOLATION (
    VIOLATION_ID int not null,
    VIOLATION_NAME VARCHAR(80),
	LAW_CODE VARCHAR(15),
    CONSTRAINT VIOLATION_ID_PK PRIMARY KEY (VIOLATION_ID)
);
CREATE TABLE dbo.CUSTOMER_STATE (
    CUSTOMER_ID INT NOT NULL,
	STATE_ID INT NOT NULL,
    CONSTRAINT CUSTOMER_ID_PK4 PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE dbo.VEHICLE_LOOKUP (
    V_VIN VARCHAR(20) NOT NULL,
    V_SERVICE VARCHAR(255) NOT NULL,
    V_CONDITION VARCHAR(255) NOT NULL,
	CONSTRAINT V_VIN_PK3 PRIMARY KEY (V_VIN)
);
------------------------------Zach------------------------------------------
CREATE TABLE dbo.SUPPLIER_PART (
	PART_ID int IDENTITY(1,1) not null,
	SUPPLIER_ID INT not null,
	CONSTRAINT PART_ID_PK PRIMARY KEY (PART_ID)
);
CREATE TABLE dbo.STATE(
	STATE_ID int not null,
	STATE_NAME varchar(30),
	CONSTRAINT STATE_ID_PK PRIMARY KEY (STATE_ID)
);
CREATE TABLE dbo.Employee_Status(
	EMPLOYEE_ID int IDENTITY(1,1) not null,
	ACTIVE_ID int not null,
	ACTIVE varchar(15)
	CONSTRAINT EMPLOYEE_ID_PK2 PRIMARY KEY (EMPLOYEE_ID)
);
CREATE TABLE dbo.STATE_VIOLATION(
	VIOLATION_ID int IDENTITY(1,1) not null,
	STATE_ID int not null
	CONSTRAINT VIOLATION_ID_PK1 PRIMARY KEY (VIOLATION_ID)
);
------------Jerry-----------------------------------------------------
--ACCOUNT REVENUE Table--
CREATE TABLE dbo.ACCOUNT_REVENUE (
	REVENUE_ID int IDENTITY(1,1) not null,
	REVENUE_NAME varchar(15),
	REVENUE_VALUE MONEY,
	CONSTRAINT REVENUE_ID_PK PRIMARY KEY (REVENUE_ID)
);
--Service Status Create--
CREATE TABLE dbo.SERVICE_STATUS (
    SERVICE_ID int NOT NULL,
    ACTIVE_ID int NOT NULL,
    ACTIVE varchar(30),
	CONSTRAINT SERVICE_ID_PK1 PRIMARY KEY (SERVICE_ID)
);
--INSURANCE COMPANY Table--
CREATE TABLE dbo.INSURANCE_COMPANY (
	INSURANCE_ID int IDENTITY(1,1) not null,
	INSURANCE_NAME varchar(40) not null,
	CONSTRAINT INSURANCE_ID_PK PRIMARY KEY (INSURANCE_ID)
);
--INSURANCE POLICY Table--
CREATE TABLE dbo.INSURANCE_POLICY (
	POLICY_ID int IDENTITY(1,1) not null,
	POLICY_NAME varchar(40),
	COVERAGE_COST MONEY,
	CONSTRAINT POLICY_ID_PK PRIMARY KEY (POLICY_ID)
);

---------------------------------------------------------------------------------------------------------------------------
--------------------------------------------- ALTER TABLE -----------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------
-------------------------Darrian-----------------------------------------------------
--Alter Service Line--
ALTER TABLE SERVICE_LINE
add CONSTRAINT SERVICE_ORDER_ID1_FK1 FOREIGN KEY (SERVICE_ORDER_ID) REFERENCES SERVICE_ORDER(SERVICE_ORDER_ID), --FIXME--
CONSTRAINT SERVICE_ID_FK2 FOREIGN KEY (SERVICE_ORDER_ID) REFERENCES SERVICE_ORDER(SERVICE_ORDER_ID); --FIXME--
/*CONSTRAINT ORDER_ID_FK1 FOREIGN KEY (ORDER_ID) REFERENCES CUSTOMER_ORDER(ORDER_ID);
CONSTRAINT SERVICE_ID_FK1 FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID);*/
--Alter Invoice Payment--
ALTER TABLE INVOICE_PAYMENT
add CONSTRAINT PMT_NUMBER_FK FOREIGN KEY (PMT_NUMBER) REFERENCES PAYMENT(PMT_NUMBER),
/* PMT_NUMBER_PK FOREIGN KEY (PMT_NUMBER) REFERENCES PAYMENT(PMT_NUMBER),*/
CONSTRAINT INVOICE_ID_FK2 FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(INVOICE_ID);

----------------------------Anthony-----------------------------------------------------
--Alter Invoice--
ALTER TABLE INVOICE
add CONSTRAINT CUSTOMER_ID_FK1 FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID);
ALTER TABLE SERVICE_ORDER_STATUS
add CONSTRAINT SERVICE_ORDER_ID_FK4 FOREIGN KEY (SERVICE_ORDER_ID) REFERENCES SERVICE_ORDER(SERVICE_ORDER_ID);

---------------------------Mustafa------------------------------------------------------
--CUSTOMER CONTACT INFO ALTER
ALTER TABLE CUSTOMER_CONTACT_INFO
add CONSTRAINT CUSTOMER_ID_FK2 FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID);
/*CONSTRAINT STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES STATE(STATE_ID);*/
----CURRENT SERVICE ALTER 
ALTER TABLE SERVICE_LINE_STATUS
add CONSTRAINT SERVICE_LINE_ID_FK1 FOREIGN KEY (SERVICE_LINE_ID) REFERENCES SERVICE_LINE(SERVICE_LINE_ID);
ALTER TABLE VEHICLE_STATUS
add CONSTRAINT V_VIN_FK6 FOREIGN KEY (V_VIN) REFERENCES VEHICLE(V_VIN);
ALTER TABLE PAYMENT_REVENUE
add CONSTRAINT REVENUE_ID_FK FOREIGN KEY (REVENUE_ID) REFERENCES ACCOUNT_REVENUE(REVENUE_ID),
CONSTRAINT PMT_NUMBER_FK1 FOREIGN KEY (PMT_NUMBER) REFERENCES PAYMENT(PMT_NUMBER);

-------------------------jahidul----------------------------------------------------------------
--Alter Customer Order--
ALTER TABLE CUSTOMER_ORDER
add CONSTRAINT SERVICE_ORDER_ID_FK2 FOREIGN KEY (SERVICE_ORDER_ID) REFERENCES SERVICE_ORDER(SERVICE_ORDER_ID),
CONSTRAINT CUSTOMER_ID_FK4 FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID);
--Alter Customer Vehicle--
ALTER TABLE CUSTOMER_VEHICLE
add CONSTRAINT V_VIN_FK2 FOREIGN KEY (V_VIN) REFERENCES VEHICLE(V_VIN),
CONSTRAINT CUSTOMER_ID_FK5 FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID);
--Alter Vehicle Policy--
ALTER TABLE VEHICLE_POLICY
add CONSTRAINT POLICY_ID_FK1 FOREIGN KEY (POLICY_ID) REFERENCES INSURANCE_POLICY(POLICY_ID),
CONSTRAINT V_VIN_FK3 FOREIGN KEY (V_VIN) REFERENCES VEHICLE(V_VIN);
--Alter Company Insurance policy--
ALTER TABLE COMPANY_INSURANCE_POLICY
add CONSTRAINT POLICY_ID_FK2 FOREIGN KEY (POLICY_ID) REFERENCES INSURANCE_POLICY(POLICY_ID),
CONSTRAINT INSURANCE_ID_FK FOREIGN KEY (INSURANCE_ID) REFERENCES INSURANCE_COMPANY(INSURANCE_ID);

---------------------------Jerry---------------------------------------------------------------
ALTER TABLE SERVICE_STATUS
add CONSTRAINT SERVICE_ID_FK4 FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID);
---------------------------Kyle---------------------------------------------------------------
--Alter Customer Status--
ALTER TABLE CUSTOMER_STATUS
add CONSTRAINT CUSTOMER_ID_FK6 FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID);
--Alter Supplier Status--
ALTER TABLE SUPPLIER_STATUS
add CONSTRAINT SUPPLIER_ID_FK1 FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID);
--Alter Vehicle Service--
ALTER TABLE VEHICLE_SERVICE
add CONSTRAINT SERVICE_ID_FK3 FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID),
CONSTRAINT V_VIN_FK4 FOREIGN KEY (V_VIN) REFERENCES VEHICLE(V_VIN);
--------------------------------Brandon--------------------------------
--Alter Employee Service Line Assignment--
ALTER TABLE EMPLOYEE_SERVICE_LINE_ASSIGNMENT
add CONSTRAINT SERVICE_LINE_ID_FK FOREIGN KEY (SERVICE_LINE_ID) REFERENCES SERVICE_LINE(SERVICE_LINE_ID),
CONSTRAINT EMPLOYEE_ID_FK3 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);
ALTER TABLE SERVICE_LINE_PART
add CONSTRAINT SERVICE_LINE_ID_FK2 FOREIGN KEY (SERVICE_LINE_ID) REFERENCES SERVICE_LINE(SERVICE_LINE_ID),
CONSTRAINT PART_ID_FK3 FOREIGN KEY (PART_ID) REFERENCES PART(PART_ID);
-----------------------------Maddy----------------------------------------------------------------
--Alter Employee Lookup--
/*ALTER TABLE SERVICE_ORDER
add CONSTRAINT SERVICE_ID1_FK FOREIGN KEY (SERVICE_ID1) REFERENCES SERVICE(SERVICE_ID);*/
ALTER TABLE EMPLOYEE_LOOKUP
add CONSTRAINT EMPLOYEE_ID_FK1 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);
ALTER TABLE CUSTOMER_TYPE
add CONSTRAINT CUSTOMER_ID_FK3 FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID);
------------------------------Gian-------------------------------------------------------------------
--ALter Vehicle Lookup--
ALTER TABLE VEHICLE_LOOKUP
add CONSTRAINT V_VIN_FK5 FOREIGN KEY (V_VIN) REFERENCES VEHICLE(V_VIN);
--ALter Supplier Lookup--
ALTER TABLE SUPPLIER_LOOKUP
add CONSTRAINT SUPPLIER_ID_FK3 FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID),
CONSTRAINT PART_ID_FK1 FOREIGN KEY (PART_ID) REFERENCES PART(PART_ID);
--Alter Customer State--
ALTER TABLE CUSTOMER_STATE
add CONSTRAINT STATE_ID_FK1 FOREIGN KEY (STATE_ID) REFERENCES STATE(STATE_ID),
CONSTRAINT CUSTOMER_ID_FK7 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_CONTACT_INFO(CUSTOMER_ID);
---------------------------Zach---------------------------------------------------------
--Alter Supplier Part--
ALTER TABLE SUPPLIER_PART
add CONSTRAINT PART_ID_FK2 FOREIGN KEY (PART_ID) REFERENCES PART(PART_ID),
CONSTRAINT SUPPLIER_ID_FK4 FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID);
--Alter Employee Status--
ALTER TABLE EMPLOYEE_STATUS
add CONSTRAINT EMPLOYEE_ID_FK2 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);
--Alter State Violation--
ALTER TABLE STATE_VIOLATION
add CONSTRAINT VIOLATION_ID_FK FOREIGN KEY (VIOLATION_ID) REFERENCES VIOLATION(VIOLATION_ID),
CONSTRAINT STATE_ID_FK2 FOREIGN KEY (STATE_ID) REFERENCES STATE(STATE_ID);

