SELECT CUSTOMER.C_FNAME AS 'First Name',
CUSTOMER.C_LNAME AS 'Last Name',
CUSTOMER.C_ADDRESS_LINE1 AS 'Customer Address',
CUSTOMER.C_CITY AS 'City',
CUSTOMER.STATE_NAME AS 'State',
CUSTOMER.C_ZIP AS 'ZIP Code',
CUSTOMER_STATUS.ACTIVE_NAME AS 'Customer Status'
FROM CUSTOMER
JOIN CUSTOMER_STATUS
ON CUSTOMER.ACTIVE_ID = CUSTOMER_STATUS.ACTIVE_ID
JOIN CUSTOMER_TYPE
ON CUSTOMER.BUSINESS_ID = CUSTOMER_TYPE.BUSINESS_ID
JOIN CUSTOMER_STATE
ON CUSTOMER.CUSTOMER_ID = CUSTOMER_STATE.CUSTOMER_ID
JOIN STATE
On STATE.STATE_ID = CUSTOMER_STATE.STATE_ID
WHERE CUSTOMER_STATUS.ACTIVE_ID IN (1,3)
ORDER BY CUSTOMER.C_LNAME;
