Select PART.PART_NAME,
SUPPLIER_PART.PART_COST As 'Part Price', 
SUPPLIER.SUPPLIER_NAME,
SUPPLIER.S_ADDRESS_LINE1 As 'Address',
SUPPLIER.S_PHONE As 'Contact no.',
SUPPLIER.S_EMAIL As 'Email Address',
SUPPLIER_STATUS.ACTIVE_NAME As 'Supplier Status'
from SUPPLIER
Join SUPPLIER_STATUS
On SUPPLIER.ACTIVE_ID=SUPPLIER_STATUS.ACTIVE_ID
Join SUPPLIER_PART
On SUPPLIER.SUPPLIER_ID=SUPPLIER_PART.SUPPLIER_ID
Join PART
On PART.PART_ID=SUPPLIER_PART.PART_ID
order by 2
