--Incomplete Orders Report--
USE ct

SELECT 
SERVICE_LINE.SERVICE_ID AS "Order ID",
SERVICE.SERVICE_TYPE AS "Type of Service",
Customer.C_LNAME AS "Last Name", 
SERVICE_ORDER.TOTAL_COST AS "Total Cost",
SERVICE.DATE_START AS "Start Date",
SERVICE.DATE_END AS "Estimated Finish Date"

From Customer
JOIN CUSTOMER_ORDER
ON Customer.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
JOIN SERVICE_ORDER
ON CUSTOMER_ORDER.SERVICE_ORDER_ID = SERVICE_ORDER.SERVICE_ORDER_ID
JOIN SERVICE_LINE
ON SERVICE_ORDER.SERVICE_ORDER_ID = SERVICE_LINE.SERVICE_ORDER_ID
JOIN SERVICE
ON SERVICE_LINE.SERVICE_ID = SERVICE.SERVICE_ID

WHERE SERVICE.DATE_END > GETDATE()
ORDER BY SERVICE.SERVICE_ID;
