--Incomplete Orders Report--
USE ct

SELECT 
SERVICE_ORDER.SERVICE_ORDER_ID AS 'Order ID',
SERVICE_ORDER.ORDER_DATE AS 'Date Ordered',
Customer.C_LNAME AS 'Last Name',
Customer.C_FNAME AS 'First Name',
INVOICE.TOTAL_COST AS 'Cost',
VEHICLE.V_LICENSE_PLATE AS 'License Plate #',
VEHICLE.V_MAKE AS 'Make',
VEHICLE.V_MODEL AS 'Model',
VEHICLE.V_YEAR AS 'Year',
VEHICLE.V_VOLOR AS 'Color'


/* Refrence
From Customer
JOIN CUSTOMER_ORDER
ON Customer.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
JOIN SERVICE_ORDER
ON CUSTOMER_ORDER.SERVICE_ORDER_ID = SERVICE_ORDER.SERVICE_ORDER_ID
JOIN SERVICE_LINE
ON SERVICE_ORDER.SERVICE_ORDER_ID = SERVICE_LINE.SERVICE_ORDER_ID
JOIN SERVICE
ON SERVICE_LINE.SERVICE_ID = SERVICE.SERVICE_ID

WHERE SERVICE.DATE_END > GETDATE()
ORDER BY SERVICE.DATE_START;
*/

From SERVICE_ORDER
Join INVOICE
On SERVICE_ORDER.SERVICE_ORDER_ID = INVOICE.SERVICE_ORDER_ID
Join Customer
On SERVICE_ORDER.CUSTOMER_ID = Customer.CUSTOMER_ID
Join CUSTOMER_VEHICLE
On Customer.CUSTOMER_ID = CUSTOMER_VEHICLE.CUSTOMER_ID
Join VEHICLE
On CUSTOMER_VEHICLE.V_ID = VEHICLE.V_ID

Where 
