USE CoogTechSolutions
CREATE TABLE dbo.VEHICLE(
	V_VIN INT NOT NULL,
	C_ID INT NOT NULL,
	V_MAKE VARCHAR, 
	V_LISCENSE_PLATE VARCHAR NOT NULL, 
	V_MODEL VARCHAR, 
	V_YEAR INT, 
	PRIMARY KEY (V_VIN),
	FOREIGN KEY (C_ID) REFERENCES Customer(C_ID)
); 
