USE CoogTechSolutions
CREATE TABLE dbo.SUPPLIER_STATUS( 
	SUPPLIER_ID INT NOT NULL, 
	SUPPLIER_ACTIVE BIT NOT NULL, 
	PRIMARY KEY (SUPPLIER_ID), 
	FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID) 
); 
