USE CoogTechSolutions
CREATE TABLE TRUCKS_IN_STORAGE ( 
  STORAGE_ID INT NOT NULL, 
  CUSTOMER_ID INT NOT NULL, 
  V_ID INT NOT NULL, 
  TIME_STORED DATETIME NOT NULL, 
  PRIMARY KEY (V_ID)  
  FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(C_ID)
); 
