USE CoogTechSolutions
CREATE TABLE dbo.[Service] (  
  SERVICE_ID INT not null,  
  SERVICE_TYPE VARCHAR(30) not null,  
  V_ID INT NOT NULL,  
  DATE_IN DATETIME NOT NULL, 
  DATE_OUT DATETIME, 
  SERVICE_RATE INT NOT NULL, 
  MATERIALS_REQUIRED VARCHAR(40) NOT NULL, 
  PRIMARY KEY (SERVICE_ID)
); 
