“SET IDENTITY_INSERT CoogTechSolutions.[dbo].[TRUCK_PART] OFF; 
INSERT INTO CoogTechSolutions.[dbo].[TRUCK_PART] ([TRCK_PRT_FURNITURE],[TRCK_PRT_FRAME],[TRCK_PRT_GATE],[TRCK_PRT_BED],[TRCK_PRT_WETLINE],[TRCK_PRT_TARP],[TRCK_PRT_FLAT_BED],[TRCK_PRT_fuel_pump],[TRCK_PRT_BENDING_MATERIAL],[TRCK_PRT_AXEL],[TRCK_PRT_WOOD]) 
VALUES (?,?,?,?,?,?,?,?,?,?,?) 
“,row.[TRCK_PRT_FURNITURE],row.[TRCK_PRT_FRAME],row.[TRCK_PRT_GATE],row.[TRCK_PRT_BED],row.[TRCK_PRT_WETLINE],row.[TRCK_PRT_TARP],row.[TRCK_PRT_FLAT_BED],row.[TRCK_PRT_fuel_pump],row.[TRCK_PRT_BENDING_MATERIAL],row.[TRCK_PRT_AXEL],row.[TRCK_PRT_WOOD]) 
