“SET IDENTITY_INSERT CoogTechSolutions.dbo.TRUCKS_IN_STORAGE OFF; 
INSERT INTO CoogTechSolutions.dbo.TRUCKS_IN_STORAGE (CUSTOMER_ID,V_ID,TIME_STORED) 
VALUES (?,?,?) 
",row.CUSTOMER_ID,row.V_ID,row.TIME_STORED) 
