“SET IDENTITY_INSERT CoogTechSolutions.dbo.TRUCKS_IN_STORAGE OFF; 
INSERT INTO CoogTechSolutions.dbo.TRUCKS_IN_STORAGE (STORAGE_ID,CUSTOMER_ID,V_ID,TIME_STORED) 
VALUES (?,?,?,?) 
",row.STORAGE_ID,row.CUSTOMER_ID,row.V_ID,row.TIME_STORED) 
