SELECT DISTINCT
Employee.EMPLOYEE_ID AS 'Employee ID',
Employee.EMPLOYEE_LNAME AS 'Employee Last Name',
Employee.EMPLOYEE_FNAME AS 'Employee First Name',
Role.ROLE_NAME AS 'Role',
Employee_Status.Active_Name AS 'Active Status'

FROM EMPLOYEE
JOIN ROLE ON EMPLOYEE.ROLE_ID = ROLE.ROLE_ID
JOIN EMPLOYEE_STATUS ON EMPLOYEE.ACTIVE_ID = EMPLOYEE_STATUS.ACTIVE_ID
JOIN EMPLOYEE_SERVICE_LINE_ASSIGNMENT ON EMPLOYEE.EMPLOYEE_ID = EMPLOYEE_SERVICE_LINE_ASSIGNMENT.EMPLOYEE_ID

ORDER BY Role.ROLE_NAME

