USE CoogTechSolutions

SELECT DISTINCT
Service.SERVICE_ID AS 'Service ID', 
Service.DATE_START AS 'Start Date', 
Service.DATE_END AS 'End Date',
Service.SERVICE_TYPE AS 'Service Type'

FROM SERVICE_LINE
JOIN SERVICE ON SERVICE_LINE.SERVICE_ID = SERVICE.SERVICE_ID
JOIN SERVICE_ORDER ON SERVICE_LINE.SERVICE_ORDER_ID = SERVICE_ORDER.SERVICE_ORDER_ID
JOIN INVOICE ON SERVICE_LINE.LINE_DATE = INVOICE.INVOICE_DATE
JOIN SERVICE_STATUS ON SERVICE.SERVICE_ID = SERVICE_STATUS.SERVICE_ID

ORDER BY SERVICE.SERVICE_ID;
