USE CoogTechSolutions
CREATE TABLE dbo.EMPLOYEE_LOOKUP (
	EMP_ID int not null,
	EMPLOYEE_CURR_SERVICE varchar(15) not null,
	PRIMARY KEY (EMP_ID),
	FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);
