"SET IDENTITY_INSERT CoogTechSolutions.dbo.CUSTOMER_TYPE OFF; 
INSERT INTO CoogTechSolutions.dbo.CUSTOMER_TYPE (CUSTOMER_ID, IS_BUSINESS, IS_INDIVIDUAL) 
VALUES (?,?,?) 
",row.CUSTOMER_ID,row.IS_BUSINESS,row.IS_INDIVIDUAL)
