“SET IDENTITY_INSERT CoogTechSolutions.dbo.EMPLOYEE_LOOKUP OFF; 
INSERT INTO CoogTechSolutions.dbo.EMPLOYEE_LOOKUP (EMPLOYEE_ID, EMPLOYEE_CURR_SERVICE) 
VALUES (?,?) 
“,row.EMPLOYEE_ID,row.EMPLOYEE_CURR_SERVICE)
