“SET IDENTITY_INSERT CoogTechSolutions.dbo.SERVICE_REQUEST OFF; 
INSERT INTO CoogTechSolutions.dbo.SERVICE_REQUEST (SERVICE_ID, SERVICE_TYPE, REQUEST_DATE) 
VALUES (?,?,?)
“,row.SERVICE_ID,row.SERVICE_TYPE,row.REQUEST_DATE)
