CREATE TABLE Service_Area(

AREA_ID int,
SERVICE_TYPE varchar(15) not null,
V_VIN int,
INVENTORY varchar(15) not null,

PRIMARY KEY(AREA_ID),
FOREIGN KEY(V_VIN) REFERENCES Service(V_VIN)
FOREIGN KEY(SERVICE_TYPE) REFERENCES Service(SERVICE_TYPE)
/*Zach Kurtubi*/
  
);
