USE CoogTechSolutions
CREATE TABLE TRUCKS_IN_STORAGE ( 
  STORAGE_ID INT NOT NULL, 
  CUSTOMER_ID INT NOT NULL, 
  V_VIN INT NOT NULL, 
  TIME_STORED DATETIME NOT NULL, 
  PRIMARY KEY (STORAGE_ID)  
  FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(C_ID),
  FOREIGN KEY (V_VIN) REFERENCES Vehicle(V_VIN)
); 
