“SET IDENTITY_INSERT CoogTechSolutions.dbo.ACCOUNT_LIABILITY OFF;
INSERT INTO CoogTechSolutions.dbo.ACCOUNT_LIABILITY (LIABILITY_NAME, LIABILITY_VALUE)
VALUES (?,?)
”,row.LIABILITY_NAME, row.LIABILITY_VALUE


