SELECT EMPLOYEE.EMPLOYEE_LNAME AS 'Last Name',
       EMPLOYEE.EMPLOYEE_FNAME AS 'First Name',
       EMPLOYEE.EMPLOYEE_PAY_RATE AS 'Hourly Pay',
       EMPLOYEE.EMPLOYEE_JOB_FUNC AS 'Job Role',
       Employee_Status.ACTIVE AS 'Status'

FROM EMPLOYEE

JOIN Employee_Status ON EMPLOYEE.EMPLOYEE_ID=Employee_Status.Employee_ID
JOIN EMPLOYEE_LOOKUP ON EMPLOYEE.EMPLOYEE_ID=EMPLOYEE_LOOKUP.EMPLOYEE_ID
JOIN EMPLOYEE_SERVICE_LINE_ASSIGNMENT ON EMPLOYEE_SERVICE_LINE_ASSIGNMENT.SERVICE_LINE_ID = SERVICE_LINE_ID
--JOIN SUPPLIER_PART ON SUPPLIER_PART.PART_ID=PART_ID



WHERE Employee_Status.ACTIVE_ID = 1

ORDER BY [Job Role],[Hourly Pay];
