USE CoogTechSolutions

SELECT SUPPLIER.SUPPLIER_ID AS 'Supplier ID',
       SUPPLIER.SUPPLIER_NAME AS 'Supplier Name',
       SUPPLIER_STATUS.ACTIVE AS 'Supplier Status'

FROM SUPPLIER

JOIN SUPPLIER_STATUS ON SUPPLIER.SUPPLIER_ID=SUPPLIER_STATUS.SUPPLIER_ID
JOIN SUPPLIER_PART ON SUPPLIER.SUPPLIER_ID=SUPPLIER_PART.SUPPLIER_ID
JOIN SUPPLIER_LOOKUP ON SUPPLIER.SUPPLIER_ID=SUPPLIER_LOOKUP.SUPPLIER_ID
--JOIN SUPPLIER_PART ON SUPPLIER_PART.PART_ID=PART.PART_ID



WHERE ACTIVE_ID = 1

ORDER BY SUPPLIER_NAME,[Supplier ID];
