SELECT EMPLOYEE.EMPLOYEE_LNAME AS 'Last Name',
       EMPLOYEE.EMPLOYEE_FNAME AS 'First Name',
       ROLE.ROLE_NAME AS 'Job Role',
       ROLE.PAY_RATE AS 'Hourly Pay',
       Employee_Status.ACTIVE_NAME AS 'Status'

FROM EMPLOYEE

JOIN Employee_Status ON EMPLOYEE.ACTIVE_ID=Employee_Status.ACTIVE_ID
JOIN ROLE ON EMPLOYEE.ROLE_ID=ROLE.ROLE_ID
JOIN EMPLOYEE_CONTACT_INFO ON EMPLOYEE.EMPLOYEE_ID = EMPLOYEE_CONTACT_INFO.EMPLOYEE_ID
JOIN EMPLOYEE_SERVICE_LINE_ASSIGNMENT ON EMPLOYEE.EMPLOYEE_ID=EMPLOYEE_SERVICE_LINE_ASSIGNMENT.EMPLOYEE_ID



WHERE Employee_Status.ACTIVE_ID = 1

ORDER BY [Job Role],[Hourly Pay];
