SELECT SUPPLIER.SUPPLIER_ID AS 'Supplier ID',
       SUPPLIER.SUPPLIER_NAME AS 'Supplier Name',
       SUPPLIER_STATUS.ACTIVE_NAME AS 'Supplier Status',
       SUPPLIER_PART.PART_ID AS 'Part ID',
       PART.PART_NAME AS 'Part Name'


FROM SUPPLIER


JOIN SUPPLIER_STATUS ON SUPPLIER.ACTIVE_ID=SUPPLIER_STATUS.ACTIVE_ID
JOIN SUPPLIER_PART ON SUPPLIER.SUPPLIER_ID=SUPPLIER.SUPPLIER_ID
JOIN PART ON SUPPLIER_PART.PART_ID=PART.PART_ID


WHERE SUPPLIER.ACTIVE_ID = 1

ORDER BY [Part ID], [Supplier Name];
