SELECT VEHICLE.V_VIN AS 'VIN Number',
       MAKE.MAKE_NAME AS 'Make',
       MODEL.MODEL_NAME AS 'Model',
       SERVICE.SERVICE_TYPE AS 'Service Done',
       SERVICE_ORDER.ORDER_DATE AS 'Date',
       CUSTOMER.C_BUSINESS_NAME AS 'Client'

FROM VEHICLE

JOIN MAKE ON VEHICLE.MAKE_ID=MAKE.MAKE_ID
JOIN MODEL ON VEHICLE.MODEL_ID=MODEL.MODEL_ID
JOIN VEHICLE_SERVICE ON VEHICLE.V_ID=VEHICLE_SERVICE.V_ID
JOIN SERVICE ON VEHICLE_SERVICE.SERVICE_ID=SERVICE.SERVICE_ID
JOIN SERVICE_LINE ON SERVICE.SERVICE_ID=SERVICE_LINE.SERVICE_ID
JOIN SERVICE_ORDER ON SERVICE_LINE.SERVICE_ORDER_ID=SERVICE_ORDER.SERVICE_ORDER_ID
JOIN CUSTOMER ON SERVICE_ORDER.CUSTOMER_ID=CUSTOMER.CUSTOMER_ID

WHERE VEHICLE.V_ID=VEHICLE_SERVICE.V_ID AND CUSTOMER.C_BUSINESS_NAME IS NOT NULL
ORDER BY [Date]
