USE CoogTechSolutions

SELECT VEHICLE.V_VIN AS 'VIN Number',
       VEHICLE.V_MAKE AS 'Make',
       VEHICLE_LOOKUP.V_SERVICE AS 'Service Done'

FROM VEHICLE

JOIN VEHICLE_LOOKUP ON VEHICLE.V_VIN=VEHICLE_LOOKUP.V_VIN
--JOIN VEHICLE_POLICY ON VEHICLE.V_VIN=VEHICLE_LOOKUP.V_VIN
--JOIN VEHICLE_SERVICE ON VEHICLE.V_VIN=VEHICLE_SERVICE.V_VIN
--JOIN VEHICLE_STATUS ON VEHICLE.V_VIN=VEHICLE_STATUS.V_VIN

WHERE VEHICLE.V_VIN=VEHICLE_LOOKUP.V_VIN

ORDER BY [VIN Number];
