SELECT EMPLOYEE.EMPLOYEE_LNAME AS 'Last Name',
       EMPLOYEE.EMPLOYEE_FNAME AS 'First Name',
       ROLE.ROLE_NAME AS 'Job Role',
       Employee_Status.ACTIVE_NAME AS 'Status'

FROM EMPLOYEE
JOIN ROLE ON EMPLOYEE.ROLE_ID=ROLE.ROLE_ID
INNER JOIN Employee_Status ON EMPLOYEE.ACTIVE_ID=Employee_Status.ACTIVE_ID



WHERE EMPLOYEE.ROLE_ID = 3
AND  Employee_Status.ACTIVE_ID = 1

ORDER BY EMPLOYEE_LNAME;
