SELECT
EMPLOYEE.EMP_FNAME AS 'First Name',
EMPLOYEE.EMP_LNAME AS 'Last Name',
SERVICE_ORDER.SERVICE_ORDER_ID AS 'Service Order ID',
SERVICE.SERVICE_TYPE AS 'Service',
SERVICE_ORDER.ORDER_DATE AS 'Order Date'

FROM EMPLOYEE
JOIN EMPLOYEE_SERVICE_LINE_ASSIGNMENT
ON EMPLOYEE.EMPLOYEE_ID = EMPLOYEE_SERVICE_LINE_ASSIGNMENT.EMPLOYEE_ID
JOIN SERVICE_LINE
ON EMPLOYEE_SERVICE_LINE_ASSIGNMENT.SERVICE_ORDER_ID = SERVICE_LINE.SERVICE_ORDER_ID
JOIN SERVICE_ORDER
ON SERVICE_LINE.SERVICE_ORDER_ID = SERVICE_ORDER.SERVICE_ORDER_ID
JOIN SERVICE_ORDER_STATUS
ON SERVICE_ORDER.ACTIVE_ID = SERVICE_ORDER_STATUS.ACTIVE_ID

JOIN SERVICE
ON SERVICE_LINE.SERVICE_ID = SERVICE.SERVICE_ID

WHERE SERVICE_ORDER.ACTIVE_ID = 2

ORDER BY SERVICE_ORDER.ORDER_DATE
