SELECT
CUSTOMER.C_FNAME AS 'Customer First Name',
CUSTOMER.C_LNAME AS 'Last Name',
VEHICLE.V_VIN AS 'Vehicle VIN',
STATE.STATE_NAME AS 'State',
VIOLATION.VIOLATION_NAME AS 'Violation',
VIOLATION.VIOLATION_DATE AS 'Violation Date',
VIOLATION.LAW_CODE AS 'Law Code'

FROM CUSTOMER
JOIN CUSTOMER_VEHICLE ON CUSTOMER.CUSTOMER_ID = CUSTOMER_VEHICLE.CUSTOMER_ID
JOIN VEHICLE ON CUSTOMER_VEHICLE.V_ID = VEHICLE.V_ID
JOIN VIOLATION ON VEHICLE.V_ID = VIOLATION.V_ID
JOIN STATE_VIOLATION ON VIOLATION.VIOLATION_ID = STATE_VIOLATION.VIOLATION_ID
JOIN STATE ON STATE_VIOLATION.STATE_ID = STATE.STATE_ID

ORDER BY VIOLATION.VIOLATION_DATE
