SELECT
VEHICLE.V_VIN AS 'VIN',
CUSTOMER.C_LNAME AS 'Customer First Name',
CUSTOMER.C_FNAME AS 'Customer Last Name',
MAKE.MAKE_NAME AS 'Make',
MODEL.MODEL_NAME AS 'Model',
VEHICLE.V_YEAR AS 'Year',
INSURANCE_COMPANY.INSURANCE_NAME AS 'Insurance',
INSURANCE_COMPANY.I_PHONE AS 'Insurance Phone Number'

FROM VEHICLE
JOIN POLICY
ON VEHICLE.V_ID = POLICY.V_ID
JOIN INSURANCE_COMPANY
ON POLICY.INSURANCE_ID = INSURANCE_COMPANY.INSURANCE_ID

JOIN CUSTOMER
ON POLICY.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID

JOIN MAKE
ON VEHICLE.MAKE_ID = MAKE.MAKE_ID

JOIN MODEL
ON VEHICLE.MODEL_ID = MODEL.MODEL_ID

JOIN VEHICLE_STATUS
ON VEHICLE.ACTIVE_ID = VEHICLE_STATUS.ACTIVE_ID

ORDER BY CUSTOMER.CUSTOMER_ID

WHERE VEHICLE_STATUS.ACTIVE_ID = 1 OR VEHICLE_STATUS.ACTIVE_ID = 3
