SELECT
VEHICLE.V_VIN AS "VIN",
VEHICLE.V_MAKE AS "Make",
VEHICLE.V_MODEL AS "Model",
VEHICLE.V_YEAR AS "Year",
INSURANCE_COMPANY.INSURANCE_NAME AS "Insurance"

FROM VEHICLE
JOIN VEHICLE_POLICY
ON VEHICLE.V_VIN = VEHICLE_POLICY.V_VIN
JOIN INSURANCE_POLICY
ON VEHICLE_POLICY.POLICY_ID = INSURANCE_POLICY.POLICY_ID
JOIN COMPANY_INSURANCE_POLICY
ON INSURANCE_POLICY.POLICY_ID = COMPANY_INSURANCE_POLICY.POLICY_ID
JOIN INSURANCE_COMPANY
ON COMPANY_INSURANCE_POLICY.POLICY_ID = INSURANCE_COMPANY.INSURANCE_ID

ORDER BY VEHICLE.V_MAKE