SELECT
CUSTOMER.C_FNAME AS 'First Name',
CUSTOMER.C_LNAME AS 'Last Name',
CUSTOMER.C_BUS_NAME AS 'Business Name',
SERVICE.SERVICE_TYPE AS 'Service Type',
INVOICE.AMT_OWED AS 'Amount Owed',
INVOICE.INVOICE_DATE AS 'Invoice Date',
MAKE.MAKE_NAME AS 'Make',
MODEL.MODEL_NAME AS 'Model',
VEHICLE.V_LICENSE_PLATE AS 'License Plate'



FROM CUSTOMER
JOIN SERVICE_ORDER ON CUSTOMER.CUSTOMER_ID = SERVICE_ORDER.CUSTOMER_ID
JOIN INVOICE ON SERVICE_ORDER.SERVICE_ORDER_ID = INVOICE.SERVICE_ORDER_ID
JOIN SERVICE_LINE ON SERVICE_ORDER.SERVICE_ORDER_ID = SERVICE_LINE.SERVICE_ORDER_ID
JOIN SERVICE ON SERVICE_LINE.SERVICE_ID = SERVICE.SERVICE_ID
JOIN VEHICLE_SERVICE ON SERVICE.SERVICE_ID = VEHICLE_SERVICE.SERVICE_ID
JOIN VEHICLE ON VEHICLE_SERVICE.V_ID = VEHICLE.V_ID
JOIN MODEL ON VEHICLE.MODEL_ID = MODEL.MODEL_ID
JOIN MAKE ON MODEL.MAKE_ID = MAKE.MAKE_ID


WHERE INVOICE.AMT_OWED > 0
