SELECT
CUSTOMER.C_FNAME AS 'Customer First Name',
CUSTOMER.C_LNAME AS 'Last Name',
VEHICLE.V_VIN AS 'Vehicle VIN',
STATE.STATE_NAME AS 'State',
VIOLATION.VIOLATION_NAME AS 'Violation',
VIOLATION.VIOLATION_DATE AS 'Violation Date',
VIOLATION.LAW_CODE AS 'Law Code'

FROM CUSTOMER
JOIN CUSTOMER_STATE
ON CUSTOMER.CUSTOMER_ID = CUSTOMER_STATE.CUSTOMER_ID
JOIN STATE
ON CUSTOMER_STATE.STATE_ID = STATE.STATE_ID
JOIN STATE_VIOLATION
ON STATE.STATE_ID = STATE_VIOLATION.STATE_ID
JOIN VIOLATION
ON STATE_VIOLATION.VIOLATION_ID = VIOLATION.VIOLATION_ID
JOIN VEHICLE
ON VIOLATION.V_ID = VEHICLE.V_ID

ORDER BY VIOLATION.VIOLATION_DATE
