SELECT
CUSTOMER.CUSTOMER_ID AS "ID",
CUSTOMER.C_FNAME AS "First Name",
CUSTOMER.C_LNAME AS "Last Name",
SERVICE.SERVICE_TYPE AS "Service Type",
INVOICE.AMT_OWED AS "Amount owed",
SERVICE.DATE_START AS "Service date"


FROM CUSTOMER
JOIN INVOICE ON CUSTOMER.CUSTOMER_ID= INVOICE.CUSTOMER_ID
JOIN CUSTOMER_ORDER ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
JOIN SERVICE_ORDER ON CUSTOMER_ORDER.SERVICE_ORDER_ID = SERVICE_ORDER.SERVICE_ORDER_ID
JOIN SERVICE_LINE ON SERVICE_ORDER.SERVICE_ORDER_ID = SERVICE_LINE.SERVICE_LINE_ID
JOIN SERVICE ON SERVICE_LINE.SERVICE_ID = SERVICE.SERVICE_ID


WHERE INVOICE.AMT_OWED > 0