SELECT
CUSTOMER.C_BUS_NAME AS "Customer",
CUSTOMER.C_LNAME AS "Last Name",
STATE.STATE_NAME AS "State",
VIOLATION.VIOLATION_NAME AS "Violation",
VIOLATION.LAW_CODE AS "Law Code"

FROM CUSTOMER
JOIN CUSTOMER_CONTACT_INFO
ON CUSTOMER.CUSTOMER_ID = CUSTOMER_CONTACT_INFO.CUSTOMER_ID
JOIN CUSTOMER_STATE
ON CUSTOMER_CONTACT_INFO.CUSTOMER_ID = CUSTOMER_STATE.CUSTOMER_ID
JOIN STATE
ON CUSTOMER_STATE.STATE_ID = STATE.STATE_ID
JOIN STATE_VIOLATION
ON STATE.STATE_ID = STATE_VIOLATION.STATE_ID
JOIN VIOLATION
ON STATE_VIOLATION.VIOLATION_ID = VIOLATION.VIOLATION_ID

ORDER BY CUSTOMER.CUSTOMER_ID