USE CoogTechSolutions
CREATE TABLE dbo.SERVICE_ORDER (
	SERVICE_ID int not null,
	C_ID int not null,
	V_VIN int not null,
	DATE_IN DATETIME not null,
	DATE_OUT DATETIME,
	SERVICE_RATE FLOAT,
	PRIMARY KEY (SERVICE_ID),
	FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE_REQUEST(SERVICE_ID),
	FOREIGN KEY (C_ID) REFERENCES Customer(C_ID),
	FOREIGN KEY (V_VIN) REFERENCES VEHICLE(V_VIN)
);