USE CoogTechSolutions
CREATE TABLE dbo.INSURANCE_POLICY (
	POLICY_ID int not null,
	INSURANCE_ID int not null,
	C_ID INT not null,
	V_VIN INT not null,
	COVERAGE_COST int,
	PRIMARY KEY (POLICY_ID),
	FOREIGN KEY (C_ID) REFERENCES Customer(C_ID),
	FOREIGN KEY (INSURANCE_ID) REFERENCES INSURANCE_COMPANY(INSURANCE_ID)

);
