--Alter Employee--
ALTER TABLE EMPLOYEE
add CONSTRAINT EMP_ID_PK PRIMARY KEY (EMP_ID);
--Alter Employee Schedule--
ALTER TABLE EMPLOYEE_SCHEDULE
add CONSTRAINT SCHEDULE_ID_PK PRIMARY KEY (SCHEDULE_ID);
--Alter Invoice--
ALTER TABLE INVOICE
add CONSTRAINT INVOICE_ID_PK PRIMARY KEY (INVOICE_ID);
--Supplier--
ALTER TABLE SUPPLIER
add CONSTRAINT SUPPLIER_ID_PK PRIMARY KEY (SUPPLIER_ID);
